# busd_usdt_coins = [
#     "ALGOBUSD",
#     "BZRXUSDT",
#     "AXSUSDT",
#     "RENUSDT",
#     "ETCBUSD",
#     "LTCUSDT",
#     "SNXUSDT",
#     "JOEBUSD",
#     "IMXUSDT",
#     "CFXUSDT",
#     "CELOBUSD",
#     "DYDXUSDT",
#     "REEFUSDT",
#     "ATOMUSDT",
#     "CREAMBUSD",
#     "AUCTIONUSDT",
#     "CELOUSDT",
#     "DFUSDT",
#     "CTSIBUSD",
#     "TLMUSDT",
#     "BTCSTUSDT",
#     "WAXPBUSD",
#     "INJUSDT",
#     "PSGBUSD",
#     "LOKABUSD",
#     "OMUSDT",
#     "DOGEUSDT",
#     "MTLBUSD",
#     "XECUSDT",
#     "KP3RBUSD",
#     "AKROUSDT",
#     "ANTUSDT",
#     "AXSBUSD",
#     "ARPABUSD",
#     "EGLDBUSD",
#     "VETUSDT",
#     "OMGBUSD",
#     "LTOBUSD",
#     "VOXELBUSD",
#     "BICOUSDT",
#     "CVXUSDT",
#     "FTTBUSD",
#     "SXPUSDT",
#     "MFTUSDT",
#     "CLVBUSD",
#     "KAVAUSDT",
#     "NANOBUSD",
#     "ALCXUSDT",
#     "DGBUSDT",
#     "KNCBUSD",
#     "CITYUSDT",
#     "HARDUSDT",
#     "XVGBUSD",
#     "TLMBUSD",
#     "TRBBUSD",
#     "FORTHBUSD",
#     "HEGICBUSD",
#     "TRXUSDT",
#     "XRPUSDT",
#     "XVGUSDT",
#     "BNXBUSD",
#     "AUTOBUSD",
#     "BATUSDT",
#     "DREPUSDT",
#     "ALGOUSDT",
#     "SKLUSDT",
#     "ONEUSDT",
#     "SXPBUSD",
#     "GTCBUSD",
#     "JASMYBUSD",
#     "RGTBUSD",
#     "CKBUSDT",
#     "BTGUSDT",
#     "WRXBUSD",
#     "AVAXBUSD",
#     "CELRUSDT",
#     "ZRXBUSD",
#     "NPXSUSDT",
#     "PERPUSDT",
#     "MDXUSDT",
#     "ANYBUSD",
#     "BURGERUSDT",
#     "IOTXUSDT",
#     "ENJUSDT",
#     "SUSHIUSDT",
#     "POLYUSDT",
#     "AMPUSDT",
#     "OGNUSDT",
#     "KSMBUSD",
#     "ACMBUSD",
#     "QUICKBUSD",
#     "COMPUSDT",
#     "ANYUSDT",
#     "FLUXUSDT",
#     "FXSUSDT",
#     "RAYBUSD",
#     "ONEBUSD",
#     "NULSBUSD",
#     "BCHABUSD",
#     "DFBUSD",
#     "CHRUSDT",
#     "AMPBUSD",
#     "BANDBUSD",
#     "GNOBUSD",
#     "WAXPUSDT",
#     "MBOXBUSD",
#     "AVAXUSDT",
#     "PLABUSD",
#     "XEMUSDT",
#     "CITYBUSD",
#     "KEEPUSDT",
#     "GTOUSDT",
#     "IDEXBUSD",
#     "AUCTIONBUSD",
#     "OMBUSD",
#     "OGUSDT",
#     "FISUSDT",
#     "CFXBUSD",
#     "BEAMUSDT",
#     "AGLDUSDT",
#     "ACHBUSD",
#     "BLZUSDT",
#     "OCEANBUSD",
#     "FORBUSD",
#     "ALPHABUSD",
#     "ALCXBUSD",
#     "API3USDT",
#     "LOKAUSDT",
#     "FLOWBUSD",
#     "UNIBUSD",
#     "KSMUSDT",
#     "1INCHBUSD",
#     "PONDUSDT",
#     "FLMUSDT",
#     "C98USDT",
#     "POLYBUSD",
#     "SCRTUSDT",
#     "BADGERBUSD",
#     "ERNBUSD",
#     "NUBUSD",
#     "ENSBUSD",
#     "ELFUSDT",
#     "LUNABUSD",
#     "TRUUSDT",
#     "PHABUSD",
#     "CVCUSDT",
#     "PORTOUSDT",
#     "RUNEBUSD",
#     "OOKIUSDT",
#     "WANUSDT",
#     "PONDBUSD",
#     "GHSTUSDT",
#     "NMRUSDT",
#     "SUNBUSD",
#     "GALAUSDT",
#     "BURGERBUSD",
#     "RSRBUSD",
#     "LSKBUSD",
#     "FISBUSD",
#     "TKOUSDT",
#     "ROSEUSDT",
#     "SUSHIBUSD",
#     "JUVUSDT",
#     "HBARUSDT",
#     "KLAYUSDT",
#     "VIDTUSDT",
#     "BONDUSDT",
#     "PLAUSDT",
#     "MOVRUSDT",
#     "WAVESUSDT",
#     "MIRUSDT",
#     "TOMOUSDT",
#     "GALABUSD",
#     "AGLDBUSD",
#     "MBOXUSDT",
#     "RIFUSDT",
#     "ZILUSDT",
#     "SRMBUSD",
#     "TORNUSDT",
#     "CVXBUSD",
#     "RSRUSDT",
#     "LINKBUSD",
#     "1INCHUSDT",
#     "KLAYBUSD",
#     "NULSUSDT",
#     "SCRTBUSD",
#     "MDXBUSD",
#     "API3BUSD",
#     "CTXCBUSD",
#     "BETABUSD",
#     "RAMPBUSD",
#     "ALICEUSDT",
#     "NEARUSDT",
#     "FETUSDT",
#     "BICOBUSD",
#     "NANOUSDT",
#     "KP3RUSDT",
#     "AERGOBUSD",
#     "TKOBUSD",
#     "VGXUSDT",
#     "UMABUSD",
#     "GRTBUSD",
#     "REEFBUSD",
#     "RVNUSDT",
#     "OXTBUSD",
#     "HNTBUSD",
#     "ELFBUSD",
#     "ALPHAUSDT",
#     "OMGUSDT",
#     "RGTUSDT",
#     "TRBUSDT",
#     "XEMBUSD",
#     "PYRBUSD",
#     "BNTBUSD",
#     "IOTABUSD",
#     "RNDRBUSD",
#     "WINGUSDT",
#     "XMRUSDT",
#     "YGGBUSD",
#     "CTSIUSDT",
#     "JUVBUSD",
#     "YGGUSDT",
#     "BCHUSDT",
#     "VIDTBUSD",
#     "ONGUSDT",
#     "QNTUSDT",
#     "ONTUSDT",
#     "BAKEBUSD",
#     "MIRBUSD",
#     "INJBUSD",
#     "CHZBUSD",
#     "ICPUSDT",
#     "WINBUSD",
#     "BADGERUSDT",
#     "TROYUSDT",
#     "IMXBUSD",
#     "DCRUSDT",
#     "EURUSDT",
#     "COCOSUSDT",
#     "FLMBUSD",
#     "OXTUSDT",
#     "CAKEBUSD",
#     "STRAXBUSD",
#     "ICXUSDT",
#     "IRISUSDT",
#     "TCTUSDT",
#     "XVSBUSD",
#     "SLPBUSD",
#     "UNFIBUSD",
#     "FORUSDT",
#     "TVKBUSD",
#     "STMXUSDT",
#     "DUSKUSDT",
#     "SPELLUSDT",
#     "IDEXUSDT",
#     "QNTBUSD",
#     "BTCSTBUSD",
#     "RADUSDT",
#     "DIAUSDT",
#     "CVPUSDT",
#     "BONDBUSD",
#     "BCHBUSD",
#     "ERNUSDT",
#     "MKRBUSD",
#     "SOLBUSD",
#     "COTIUSDT",
#     "XRPBUSD",
#     "COSUSDT",
#     "CKBBUSD",
#     "EGLDUSDT",
#     "BTTUSDT",
#     "COVERBUSD",
#     "QUICKUSDT",
#     "DASHBUSD",
#     "NMRBUSD",
#     "XTZUSDT",
#     "GXSUSDT",
#     "SWRVBUSD",
#     "DNTBUSD",
#     "HNTUSDT",
#     "MLNUSDT",
#     "LINAUSDT",
#     "PSGUSDT",
#     "SUNUSDT",
#     "REPUSDT",
#     "OOKIBUSD",
#     "ANKRBUSD",
#     "ADXBUSD",
#     "PUNDIXUSDT",
#     "STMXBUSD",
#     "ARBUSD",
#     "TRUBUSD",
#     "CLVUSDT",
#     "GNOUSDT",
#     "COCOSBUSD",
#     "SUPERBUSD",
#     "FRONTUSDT",
#     "LPTUSDT",
#     "BTSUSDT",
#     "ASRUSDT",
#     "YFIBUSD",
#     "YFIIBUSD",
#     "JSTBUSD",
#     "FIOBUSD",
#     "DENTBUSD",
#     "ILVUSDT",
#     "TFUELUSDT",
#     "UMAUSDT",
#     "BANDUSDT",
#     "AUDIOUSDT",
#     "RADBUSD",
#     "CHESSBUSD",
#     "CRVUSDT",
#     "FIOUSDT",
#     "QTUMBUSD",
#     "THETAUSDT",
#     "LUNAUSDT",
#     "KMDUSDT",
#     "CTXCUSDT",
#     "FORTHUSDT",
#     "BTGBUSD",
#     "BNBBUSD",
#     "ZECBUSD",
#     "PHAUSDT",
#     "DNTUSDT",
#     "SPELLBUSD",
#     "LITBUSD",
#     "BARBUSD",
#     "WTCUSDT",
#     "SHIBUSDT",
#     "STPTUSDT",
#     "FILBUSD",
#     "PEOPLEUSDT",
#     "ORNUSDT",
#     "AIONUSDT",
#     "SYSUSDT",
#     "MATICUSDT",
#     "DGBBUSD",
#     "DOTUSDT",
#     "POLSBUSD",
#     "GRTUSDT",
#     "TVKUSDT",
#     "ATMUSDT",
#     "NEARBUSD",
#     "BIFIBUSD",
#     "BNXUSDT",
#     "DARUSDT",
#     "PYRUSDT",
#     "SYSBUSD",
#     "FXSBUSD",
#     "REQUSDT",
#     "FUNUSDT",
#     "ENJBUSD",
#     "XLMUSDT",
#     "NUUSDT",
#     "PAXGUSDT",
#     "SKLBUSD",
#     "CVPBUSD",
#     "WRXUSDT",
#     "MKRUSDT",
#     "ARDRUSDT",
#     "PNTUSDT",
#     "PROMBUSD",
#     "HIGHUSDT",
#     "ATABUSD",
#     "ALPACABUSD",
#     "ARUSDT",
#     "RLCBUSD",
#     "FARMBUSD",
#     "RAYUSDT",
#     "ZENUSDT",
#     "LRCUSDT",
#     "JASMYUSDT",
#     "LAZIOUSDT",
#     "WNXMUSDT",
#     "ADAUSDT",
#     "TRXBUSD",
#     "TWTBUSD",
#     "ORNBUSD",
#     "SANDBUSD",
#     "MASKBUSD",
#     "TWTUSDT",
#     "STXBUSD",
#     "ADXUSDT",
#     "THETABUSD",
#     "HOTBUSD",
#     "UNIUSDT",
#     "HIVEUSDT",
#     "ZECUSDT",
#     "MCBUSD",
#     "CHZUSDT",
#     "AUDBUSD",
#     "GLMRBUSD",
#     "MBLUSDT",
#     "RAMPUSDT",
#     "PERPBUSD",
#     "BALUSDT",
#     "FTMBUSD",
#     "FIDABUSD",
#     "DUSKBUSD",
#     "MDTUSDT",
#     "TROYBUSD",
#     "WINUSDT",
#     "TRIBEUSDT",
#     "TOMOBUSD",
#     "SOLUSDT",
#     "DOGEBUSD",
#     "MITHUSDT",
#     "BNBUSDT",
#     "GBPBUSD",
#     "ATAUSDT",
#     "EOSBUSD",
#     "IOSTUSDT",
#     "STORJBUSD",
#     "UNFIUSDT",
#     "GLMRUSDT",
#     "DASHUSDT",
#     "MTLUSDT",
#     "FILUSDT",
#     "COTIBUSD",
#     "HIGHBUSD",
#     "AUDIOBUSD",
#     "BALBUSD",
#     "KEYUSDT",
#     "POWRBUSD",
#     "SANTOSUSDT",
#     "BELBUSD",
#     "DODOUSDT",
#     "SRMUSDT",
#     "DEGOUSDT",
#     "VOXELUSDT",
#     "ICPBUSD",
#     "HIVEBUSD",
#     "MANABUSD",
#     "DATAUSDT",
#     "DYDXBUSD",
#     "AAVEUSDT",
#     "VTHOUSDT",
#     "QIBUSD",
#     "COSBUSD",
#     "DODOBUSD",
#     "SNXBUSD",
#     "COMPBUSD",
#     "RAREBUSD",
#     "DARBUSD",
#     "UFTBUSD",
#     "PAXGBUSD",
#     "NBSUSDT",
#     "QIUSDT",
#     "FLUXBUSD",
#     "VITEUSDT",
#     "EPSUSDT",
#     "SANDUSDT",
#     "XVSUSDT",
#     "ACHUSDT",
#     "AVABUSD",
#     "MOVRBUSD",
#     "XMRBUSD",
#     "JSTUSDT",
#     "ONTBUSD",
#     "SCBUSD",
#     "LTCBUSD",
#     "RNDRUSDT",
#     "STXUSDT",
#     "LINKUSDT",
#     "LINABUSD",
#     "MANAUSDT",
#     "ICXBUSD",
#     "POLSUSDT",
#     "LSKUSDT",
#     "ROSEBUSD",
#     "DENTUSDT",
#     "ZENBUSD",
#     "RUNEUSDT",
#     "DIABUSD",
#     "NEOBUSD",
#     "AUDUSDT",
#     "FETBUSD",
#     "NKNUSDT",
#     "ARPAUSDT",
#     "EOSUSDT",
#     "UTKBUSD",
#     "BZRXBUSD",
#     "PERLUSDT",
#     "JOEUSDT",
#     "BATBUSD",
#     "KNCUSDT",
#     "CTKBUSD",
#     "OCEANUSDT",
#     "DOCKBUSD",
#     "GBPUSDT",
#     "FIDAUSDT",
#     "IOTAUSDT",
#     "FIROUSDT",
#     "DEXEUSDT",
#     "XTZBUSD",
#     "EPSBUSD",
#     "GTCUSDT",
#     "CHRBUSD",
#     "BNTUSDT",
#     "CELRBUSD",
#     "LAZIOBUSD",
#     "ATOMBUSD",
#     "CRVBUSD",
#     "NEOUSDT",
#     "CAKEUSDT",
#     "DOCKUSDT",
#     "SUPERUSDT",
#     "MDTBUSD",
#     "RAREUSDT",
#     "ENSUSDT",
#     "AUTOUSDT",
#     "DEXEBUSD",
#     "BTTBUSD",
#     "STRAXUSDT",
#     "MINAUSDT",
#     "KAVABUSD",
#     "RENBUSD",
#     "BAKEUSDT",
#     "TORNBUSD",
#     "IOTXBUSD",
#     "SCUSDT",
#     "QTUMUSDT",
#     "DATABUSD",
#     "UTKUSDT",
#     "BARUSDT",
#     "RVNBUSD",
#     "ZILBUSD",
#     "C98BUSD",
#     "YFIUSDT",
#     "XECBUSD",
#     "KEEPBUSD",
#     "BETAUSDT",
#     "AAVEBUSD",
#     "CTKUSDT",
#     "OGNBUSD",
#     "RLCUSDT",
#     "MLNBUSD",
#     "REQBUSD",
#     "ANTBUSD",
#     "LRCBUSD",
#     "HBARBUSD",
#     "LTOUSDT",
#     "LPTBUSD",
#     "ADABUSD",
#     "YFIIUSDT",
#     "ALICEBUSD",
#     "FLOWUSDT",
#     "TRIBEBUSD",
#     "SFPBUSD",
#     "STPTBUSD",
#     "FARMUSDT",
#     "IQBUSD",
#     "BELUSDT",
#     "POWRUSDT",
#     "CHESSUSDT",
#     "SLPUSDT",
#     "SUSDUSDT",
#     "HARDBUSD",
#     "SHIBBUSD",
#     "ETCUSDT",
#     "MASKUSDT",
#     "GHSTBUSD",
#     "DEGOBUSD",
#     "LITUSDT",
#     "MATICBUSD",
#     "ALPACAUSDT",
#     "HOTUSDT",
#     "ZRXUSDT",
#     "MINABUSD",
#     "WAVESBUSD",
#     "FTTUSDT",
#     "STORJUSDT",
#     "FTMUSDT",
#     "PEOPLEBUSD",
#     "AVAUSDT",
#     "DOTBUSD",
#     "SFPUSDT",
#     "ATMBUSD",
#     "ACMUSDT",
#     "ANKRUSDT",
#     "XLMBUSD",
#     "WINGBUSD",
#     "FRONTBUSD",
#     "ILVBUSD",
#     "IOSTBUSD",
#     "VETBUSD",
# ]

# all_coins = [
#     "ALGOBUSD",
#     "BZRXUSDT",
#     "AXSUSDT",
#     "RENUSDT",
#     "ETCBUSD",
#     "LTCUSDT",
#     "SNXUSDT",
#     "JOEBUSD",
#     "IMXUSDT",
#     "CFXUSDT",
#     "CELOBUSD",
#     "DYDXUSDT",
#     "REEFUSDT",
#     "ATOMUSDT",
#     "CREAMBUSD",
#     "AUCTIONUSDT",
#     "CELOUSDT",
#     "DFUSDT",
#     "CTSIBUSD",
#     "TLMUSDT",
#     "BTCSTUSDT",
#     "WAXPBUSD",
#     "INJUSDT",
#     "PSGBUSD",
#     "LOKABUSD",
#     "USDCBUSD",
#     "OMUSDT",
#     "DOGEUSDT",
#     "MTLBUSD",
#     "XECUSDT",
#     "KP3RBUSD",
#     "AKROUSDT",
#     "BEARUSDT",
#     "BNBBEARUSDT",
#     "ANTUSDT",
#     "ETHUSDT",
#     "AXSBUSD",
#     "ARPABUSD",
#     "EGLDBUSD",
#     "VETUSDT",
#     "OMGBUSD",
#     "LTOBUSD",
#     "VOXELBUSD",
#     "BICOUSDT",
#     "CVXUSDT",
#     "FTTBUSD",
#     "SXPUSDT",
#     "MFTUSDT",
#     "CLVBUSD",
#     "EURBUSD",
#     "KAVAUSDT",
#     "NANOBUSD",
#     "ALCXUSDT",
#     "XRPBULLBUSD",
#     "XZCUSDT",
#     "DGBUSDT",
#     "KNCBUSD",
#     "CITYUSDT",
#     "HARDUSDT",
#     "XVGBUSD",
#     "TLMBUSD",
#     "TRBBUSD",
#     "FORTHBUSD",
#     "HEGICBUSD",
#     "TRXUSDT",
#     "XRPUSDT",
#     "ERDUSDT",
#     "XVGUSDT",
#     "BNXBUSD",
#     "AUTOBUSD",
#     "BATUSDT",
#     "DREPUSDT",
#     "ALGOUSDT",
#     "SKLUSDT",
#     "ONEUSDT",
#     "TUSDBUSD",
#     "SXPBUSD",
#     "DCRBUSD",
#     "GTCBUSD",
#     "JASMYBUSD",
#     "RGTBUSD",
#     "CKBUSDT",
#     "BTGUSDT",
#     "WRXBUSD",
#     "AVAXBUSD",
#     "BULLBUSD",
#     "WNXMBUSD",
#     "CELRUSDT",
#     "ZRXBUSD",
#     "AIONBUSD",
#     "NPXSUSDT",
#     "PERPUSDT",
#     "STRATBUSD",
#     "MDXUSDT",
#     "ANYBUSD",
#     "BURGERUSDT",
#     "IOTXUSDT",
#     "ENJUSDT",
#     "SUSHIUSDT",
#     "POLYUSDT",
#     "AMPUSDT",
#     "OGNUSDT",
#     "KSMBUSD",
#     "ACMBUSD",
#     "QUICKBUSD",
#     "COMPUSDT",
#     "USTBUSD",
#     "ANYUSDT",
#     "FLUXUSDT",
#     "FXSUSDT",
#     "PAXUSDT",
#     "RAYBUSD",
#     "ONEBUSD",
#     "NULSBUSD",
#     "BCHABUSD",
#     "DFBUSD",
#     "CHRUSDT",
#     "AMPBUSD",
#     "BANDBUSD",
#     "GNOBUSD",
#     "WAXPUSDT",
#     "MBOXBUSD",
#     "AVAXUSDT",
#     "ETHBUSD",
#     "PLABUSD",
#     "XEMUSDT",
#     "CITYBUSD",
#     "KEEPUSDT",
#     "XRPBULLUSDT",
#     "GTOUSDT",
#     "IDEXBUSD",
#     "AUCTIONBUSD",
#     "OMBUSD",
#     "OGUSDT",
#     "FISUSDT",
#     "CFXBUSD",
#     "BEAMUSDT",
#     "AGLDUSDT",
#     "ACHBUSD",
#     "BLZUSDT",
#     "OCEANBUSD",
#     "USDSBUSDT",
#     "FORBUSD",
#     "ALPHABUSD",
#     "ALCXBUSD",
#     "API3USDT",
#     "LOKAUSDT",
#     "IRISBUSD",
#     "FLOWBUSD",
#     "UNIBUSD",
#     "KSMUSDT",
#     "1INCHBUSD",
#     "PONDUSDT",
#     "FLMUSDT",
#     "C98USDT",
#     "POLYBUSD",
#     "BCHABCBUSD",
#     "SCRTUSDT",
#     "BADGERBUSD",
#     "ERNBUSD",
#     "NUBUSD",
#     "ENSBUSD",
#     "ELFUSDT",
#     "MCOUSDT",
#     "LUNABUSD",
#     "TRUUSDT",
#     "PHABUSD",
#     "CVCUSDT",
#     "PORTOUSDT",
#     "RUNEBUSD",
#     "OOKIUSDT",
#     "WANUSDT",
#     "PONDBUSD",
#     "GHSTUSDT",
#     "NMRUSDT",
#     "SUNBUSD",
#     "GALAUSDT",
#     "BURGERBUSD",
#     "RSRBUSD",
#     "LSKBUSD",
#     "FISBUSD",
#     "TKOUSDT",
#     "ROSEUSDT",
#     "SUSHIBUSD",
#     "JUVUSDT",
#     "HBARUSDT",
#     "KLAYUSDT",
#     "VIDTUSDT",
#     "BONDUSDT",
#     "PLAUSDT",
#     "MOVRUSDT",
#     "WAVESUSDT",
#     "MIRUSDT",
#     "TOMOUSDT",
#     "USDCUSDT",
#     "GALABUSD",
#     "AGLDBUSD",
#     "MBOXUSDT",
#     "RIFUSDT",
#     "ZILUSDT",
#     "SRMBUSD",
#     "TORNUSDT",
#     "CVXBUSD",
#     "RSRUSDT",
#     "LINKBUSD",
#     "1INCHUSDT",
#     "KLAYBUSD",
#     "NULSUSDT",
#     "SCRTBUSD",
#     "DAIUSDT",
#     "MDXBUSD",
#     "API3BUSD",
#     "CTXCBUSD",
#     "BETABUSD",
#     "RAMPBUSD",
#     "ALICEUSDT",
#     "NEARUSDT",
#     "FETUSDT",
#     "BICOBUSD",
#     "NANOUSDT",
#     "KP3RUSDT",
#     "AERGOBUSD",
#     "TKOBUSD",
#     "VGXUSDT",
#     "BUSDUSDT",
#     "UMABUSD",
#     "GRTBUSD",
#     "REEFBUSD",
#     "RVNUSDT",
#     "ETHBEARUSDT",
#     "OXTBUSD",
#     "HNTBUSD",
#     "ELFBUSD",
#     "ALPHAUSDT",
#     "OMGUSDT",
#     "VTHOBUSD",
#     "RGTUSDT",
#     "TRBUSDT",
#     "XEMBUSD",
#     "PYRBUSD",
#     "BNTBUSD",
#     "IOTABUSD",
#     "RNDRBUSD",
#     "WINGUSDT",
#     "XMRUSDT",
#     "YGGBUSD",
#     "CTSIUSDT",
#     "JUVBUSD",
#     "YGGUSDT",
#     "BCHUSDT",
#     "VIDTBUSD",
#     "ONGUSDT",
#     "QNTUSDT",
#     "ONTUSDT",
#     "BAKEBUSD",
#     "MIRBUSD",
#     "INJBUSD",
#     "CHZBUSD",
#     "USDPUSDT",
#     "ICPUSDT",
#     "WINBUSD",
#     "BADGERUSDT",
#     "TROYUSDT",
#     "IMXBUSD",
#     "VENUSDT",
#     "DCRUSDT",
#     "EURUSDT",
#     "COCOSUSDT",
#     "FLMBUSD",
#     "OXTUSDT",
#     "CAKEBUSD",
#     "BNBBEARBUSD",
#     "STRAXBUSD",
#     "ICXUSDT",
#     "IRISUSDT",
#     "TCTUSDT",
#     "XVSBUSD",
#     "SLPBUSD",
#     "UNFIBUSD",
#     "FORUSDT",
#     "TVKBUSD",
#     "STMXUSDT",
#     "XRPBEARUSDT",
#     "DUSKUSDT",
#     "SPELLUSDT",
#     "IDEXUSDT",
#     "QNTBUSD",
#     "BTCSTBUSD",
#     "RADUSDT",
#     "DIAUSDT",
#     "CVPUSDT",
#     "BONDBUSD",
#     "USDSUSDT",
#     "BCHBUSD",
#     "HCUSDT",
#     "ERNUSDT",
#     "MKRBUSD",
#     "SOLBUSD",
#     "COTIUSDT",
#     "XRPBUSD",
#     "COSUSDT",
#     "CKBBUSD",
#     "EGLDUSDT",
#     "ETHBULLUSDT",
#     "BTTUSDT",
#     "COVERBUSD",
#     "QUICKUSDT",
#     "DASHBUSD",
#     "NMRBUSD",
#     "XTZUSDT",
#     "GXSUSDT",
#     "SWRVBUSD",
#     "DNTBUSD",
#     "BULLUSDT",
#     "HNTUSDT",
#     "MLNUSDT",
#     "LINAUSDT",
#     "ETHBULLBUSD",
#     "PSGUSDT",
#     "SUNUSDT",
#     "REPUSDT",
#     "OOKIBUSD",
#     "ANKRBUSD",
#     "ADXBUSD",
#     "PUNDIXUSDT",
#     "STMXBUSD",
#     "ARBUSD",
#     "TRUBUSD",
#     "CLVUSDT",
#     "GNOUSDT",
#     "COCOSBUSD",
#     "SUPERBUSD",
#     "FRONTUSDT",
#     "LPTUSDT",
#     "BTSUSDT",
#     "ASRUSDT",
#     "YFIBUSD",
#     "YFIIBUSD",
#     "BNBBULLUSDT",
#     "JSTBUSD",
#     "FIOBUSD",
#     "DENTBUSD",
#     "ILVUSDT",
#     "TFUELUSDT",
#     "UMAUSDT",
#     "BANDUSDT",
#     "AUDIOUSDT",
#     "RADBUSD",
#     "BNBBULLBUSD",
#     "CHESSBUSD",
#     "CRVUSDT",
#     "FIOUSDT",
#     "QTUMBUSD",
#     "THETAUSDT",
#     "LUNAUSDT",
#     "KMDUSDT",
#     "LENDUSDT",
#     "CTXCUSDT",
#     "FORTHUSDT",
#     "LENDBUSD",
#     "BTGBUSD",
#     "DAIBUSD",
#     "BNBBUSD",
#     "ZECBUSD",
#     "BTCBUSD",
#     "PHAUSDT",
#     "DNTUSDT",
#     "SPELLBUSD",
#     "LITBUSD",
#     "BARBUSD",
#     "WTCUSDT",
#     "SHIBUSDT",
#     "STPTUSDT",
#     "FILBUSD",
#     "STRATUSDT",
#     "PEOPLEUSDT",
#     "ORNUSDT",
#     "AIONUSDT",
#     "SYSUSDT",
#     "MATICUSDT",
#     "DGBBUSD",
#     "BCHSVUSDT",
#     "DOTUSDT",
#     "POLSBUSD",
#     "GRTUSDT",
#     "TVKUSDT",
#     "ATMUSDT",
#     "NEARBUSD",
#     "BIFIBUSD",
#     "BNXUSDT",
#     "DARUSDT",
#     "STORMUSDT",
#     "PYRUSDT",
#     "SYSBUSD",
#     "FXSBUSD",
#     "REQUSDT",
#     "FUNUSDT",
#     "ENJBUSD",
#     "XLMUSDT",
#     "NUUSDT",
#     "BTSBUSD",
#     "USTUSDT",
#     "PAXGUSDT",
#     "SKLBUSD",
#     "CVPBUSD",
#     "WRXUSDT",
#     "MKRUSDT",
#     "ARDRUSDT",
#     "PNTUSDT",
#     "PROMBUSD",
#     "HIGHUSDT",
#     "EOSBEARUSDT",
#     "ATABUSD",
#     "ALPACABUSD",
#     "ARUSDT",
#     "RLCBUSD",
#     "FARMBUSD",
#     "RAYUSDT",
#     "ZENUSDT",
#     "LRCUSDT",
#     "JASMYUSDT",
#     "LAZIOUSDT",
#     "WNXMUSDT",
#     "ADAUSDT",
#     "TRXBUSD",
#     "TWTBUSD",
#     "ORNBUSD",
#     "SANDBUSD",
#     "BTCUSDT",
#     "MASKBUSD",
#     "TWTUSDT",
#     "STXBUSD",
#     "ADXUSDT",
#     "THETABUSD",
#     "HOTBUSD",
#     "UNIUSDT",
#     "HIVEUSDT",
#     "ZECUSDT",
#     "MCBUSD",
#     "CHZUSDT",
#     "BOTBUSD",
#     "BLZBUSD",
#     "AUDBUSD",
#     "GLMRBUSD",
#     "MBLUSDT",
#     "RAMPUSDT",
#     "PERPBUSD",
#     "BALUSDT",
#     "FTMBUSD",
#     "FIDABUSD",
#     "DUSKBUSD",
#     "MDTUSDT",
#     "TROYBUSD",
#     "ERDBUSD",
#     "WINUSDT",
#     "TRIBEUSDT",
#     "TOMOBUSD",
#     "SOLUSDT",
#     "DOGEBUSD",
#     "MITHUSDT",
#     "BNBUSDT",
#     "GBPBUSD",
#     "ATAUSDT",
#     "EOSBUSD",
#     "IOSTUSDT",
#     "STORJBUSD",
#     "UNFIUSDT",
#     "GLMRUSDT",
#     "DASHUSDT",
#     "MTLUSDT",
#     "FILUSDT",
#     "COTIBUSD",
#     "HIGHBUSD",
#     "AUDIOBUSD",
#     "BALBUSD",
#     "KEYUSDT",
#     "POWRBUSD",
#     "SANTOSUSDT",
#     "BELBUSD",
#     "DODOUSDT",
#     "SRMUSDT",
#     "DEGOUSDT",
#     "VOXELUSDT",
#     "ICPBUSD",
#     "HIVEBUSD",
#     "MANABUSD",
#     "DATAUSDT",
#     "DYDXBUSD",
#     "AAVEUSDT",
#     "XRPBEARBUSD",
#     "VTHOUSDT",
#     "QIBUSD",
#     "COSBUSD",
#     "DODOBUSD",
#     "SNXBUSD",
#     "COMPBUSD",
#     "RAREBUSD",
#     "DARBUSD",
#     "UFTBUSD",
#     "PAXGBUSD",
#     "PAXBUSD",
#     "NBSUSDT",
#     "QIUSDT",
#     "FLUXBUSD",
#     "EOSBULLBUSD",
#     "VITEUSDT",
#     "EPSUSDT",
#     "SANDUSDT",
#     "XVSUSDT",
#     "ACHUSDT",
#     "AVABUSD",
#     "MOVRBUSD",
#     "XMRBUSD",
#     "JSTUSDT",
#     "ONTBUSD",
#     "SCBUSD",
#     "LTCBUSD",
#     "RNDRUSDT",
#     "REPBUSD",
#     "STXUSDT",
#     "LINKUSDT",
#     "LINABUSD",
#     "MANAUSDT",
#     "ICXBUSD",
#     "POLSUSDT",
#     "LSKUSDT",
#     "ROSEBUSD",
#     "DENTUSDT",
#     "ZENBUSD",
#     "RUNEUSDT",
#     "DIABUSD",
#     "NEOBUSD",
#     "AUDUSDT",
#     "FETBUSD",
#     "NKNUSDT",
#     "BCHABCUSDT",
#     "ARPAUSDT",
#     "EOSUSDT",
#     "UTKBUSD",
#     "BZRXBUSD",
#     "PERLUSDT",
#     "JOEUSDT",
#     "ETHBEARBUSD",
#     "TUSDUSDT",
#     "BKRWBUSD",
#     "BATBUSD",
#     "KNCUSDT",
#     "CTKBUSD",
#     "OCEANUSDT",
#     "DOCKBUSD",
#     "GBPUSDT",
#     "FIDAUSDT",
#     "IOTAUSDT",
#     "FIROUSDT",
#     "DEXEUSDT",
#     "XTZBUSD",
#     "EPSBUSD",
#     "GTCUSDT",
#     "CHRBUSD",
#     "BNTUSDT",
#     "CELRBUSD",
#     "LAZIOBUSD",
#     "ATOMBUSD",
#     "CRVBUSD",
#     "NEOUSDT",
#     "CAKEUSDT",
#     "USDPBUSD",
#     "DOCKUSDT",
#     "SUPERUSDT",
#     "MDTBUSD",
#     "RAREUSDT",
#     "BKRWUSDT",
#     "ENSUSDT",
#     "AUTOUSDT",
#     "DEXEBUSD",
#     "KMDBUSD",
#     "BTTBUSD",
#     "STRAXUSDT",
#     "MINAUSDT",
#     "KAVABUSD",
#     "RENBUSD",
#     "BAKEUSDT",
#     "TORNBUSD",
#     "IOTXBUSD",
#     "SCUSDT",
#     "QTUMUSDT",
#     "EOSBULLUSDT",
#     "DATABUSD",
#     "UTKUSDT",
#     "BARUSDT",
#     "RVNBUSD",
#     "ZILBUSD",
#     "C98BUSD",
#     "YFIUSDT",
#     "XECBUSD",
#     "KEEPBUSD",
#     "BETAUSDT",
#     "AAVEBUSD",
#     "BCCUSDT",
#     "CTKUSDT",
#     "OGNBUSD",
#     "RLCUSDT",
#     "MLNBUSD",
#     "REQBUSD",
#     "ANTBUSD",
#     "LRCBUSD",
#     "HBARBUSD",
#     "LTOUSDT",
#     "LPTBUSD",
#     "ADABUSD",
#     "YFIIUSDT",
#     "MCUSDT",
#     "ALICEBUSD",
#     "FLOWUSDT",
#     "TRIBEBUSD",
#     "SFPBUSD",
#     "STPTBUSD",
#     "FARMUSDT",
#     "IQBUSD",
#     "BELUSDT",
#     "EOSBEARBUSD",
#     "POWRUSDT",
#     "CHESSUSDT",
#     "SLPUSDT",
#     "SUSDUSDT",
#     "HARDBUSD",
#     "SHIBBUSD",
#     "ETCUSDT",
#     "MASKUSDT",
#     "GHSTBUSD",
#     "DEGOBUSD",
#     "LITUSDT",
#     "MATICBUSD",
#     "ALPACAUSDT",
#     "HOTUSDT",
#     "ZRXUSDT",
#     "MINABUSD",
#     "WAVESBUSD",
#     "FTTUSDT",
#     "STORJUSDT",
#     "FTMUSDT",
#     "PEOPLEBUSD",
#     "AVAUSDT",
#     "DOTBUSD",
#     "SFPUSDT",
#     "ATMBUSD",
#     "ACMUSDT",
#     "BEARBUSD",
#     "ANKRUSDT",
#     "XLMBUSD",
#     "WINGBUSD",
#     "FRONTBUSD",
#     "ILVBUSD",
#     "IOSTBUSD",
#     "VETBUSD",
# ]

valuable_coins = [
    "BZRXUSDT",
    "AXSUSDT",
    "RENUSDT",
    "LTCUSDT",
    "SNXUSDT",
    "IMXUSDT",
    "CFXUSDT",
    "DYDXUSDT",
    "REEFUSDT",
    "ATOMUSDT",
    "AUCTIONUSDT",
    "CELOUSDT",
    "DFUSDT",
    "TLMUSDT",
    "BTCSTUSDT",
    "INJUSDT",
    "OMUSDT",
    "DOGEUSDT",
    "XECUSDT",
    "AKROUSDT",
    "ANTUSDT",
    "VETUSDT",
    "BICOUSDT",
    "CVXUSDT",
    "SXPUSDT",
    "MFTUSDT",
    "KAVAUSDT",
    "ALCXUSDT",
    "DGBUSDT",
    "CITYUSDT",
    "HARDUSDT",
    "TRXUSDT",
    "XRPUSDT",
    "XVGUSDT",
    "BATUSDT",
    "DREPUSDT",
    "ALGOUSDT",
    "SKLUSDT",
    "ONEUSDT",
    "CKBUSDT",
    "BTGUSDT",
    "CELRUSDT",
    "NPXSUSDT",
    "PERPUSDT",
    "MDXUSDT",
    "BURGERUSDT",
    "IOTXUSDT",
    "ENJUSDT",
    "SUSHIUSDT",
    "POLYUSDT",
    "AMPUSDT",
    "OGNUSDT",
    "COMPUSDT",
    "ANYUSDT",
    "FLUXUSDT",
    "FXSUSDT",
    "CHRUSDT",
    "WAXPUSDT",
    "AVAXUSDT",
    "XEMUSDT",
    "KEEPUSDT",
    "GTOUSDT",
    "OGUSDT",
    "FISUSDT",
    "BEAMUSDT",
    "AGLDUSDT",
    "BLZUSDT",
    "API3USDT",
    "LOKAUSDT",
    "KSMUSDT",
    "PONDUSDT",
    "FLMUSDT",
    "C98USDT",
    "SCRTUSDT",
    "ELFUSDT",
    "TRUUSDT",
    "CVCUSDT",
    "PORTOUSDT",
    "OOKIUSDT",
    "WANUSDT",
    "GHSTUSDT",
    "NMRUSDT",
    "GALAUSDT",
    "TKOUSDT",
    "ROSEUSDT",
    "JUVUSDT",
    "HBARUSDT",
    "KLAYUSDT",
    "VIDTUSDT",
    "BONDUSDT",
    "PLAUSDT",
    "MOVRUSDT",
    "WAVESUSDT",
    "MIRUSDT",
    "TOMOUSDT",
    "MBOXUSDT",
    "RIFUSDT",
    "ZILUSDT",
    "TORNUSDT",
    "RSRUSDT",
    "1INCHUSDT",
    "NULSUSDT",
    "ALICEUSDT",
    "NEARUSDT",
    "FETUSDT",
    "NANOUSDT",
    "KP3RUSDT",
    "VGXUSDT",
    "RVNUSDT",
    "ALPHAUSDT",
    "OMGUSDT",
    "RGTUSDT",
    "TRBUSDT",
    "WINGUSDT",
    "XMRUSDT",
    "CTSIUSDT",
    "YGGUSDT",
    "BCHUSDT",
    "ONGUSDT",
    "QNTUSDT",
    "ONTUSDT",
    "ICPUSDT",
    "BADGERUSDT",
    "TROYUSDT",
    "DCRUSDT",
    "EURUSDT",
    "COCOSUSDT",
    "OXTUSDT",
    "ICXUSDT",
    "IRISUSDT",
    "TCTUSDT",
    "FORUSDT",
    "STMXUSDT",
    "DUSKUSDT",
    "SPELLUSDT",
    "IDEXUSDT",
    "RADUSDT",
    "DIAUSDT",
    "CVPUSDT",
    "ERNUSDT",
    "COTIUSDT",
    "COSUSDT",
    "EGLDUSDT",
    "BTTUSDT",
    "QUICKUSDT",
    "XTZUSDT",
    "GXSUSDT",
    "HNTUSDT",
    "MLNUSDT",
    "LINAUSDT",
    "PSGUSDT",
    "SUNUSDT",
    "REPUSDT",
    "PUNDIXUSDT",
    "CLVUSDT",
    "GNOUSDT",
    "FRONTUSDT",
    "LPTUSDT",
    "BTSUSDT",
    "ASRUSDT",
    "ILVUSDT",
    "TFUELUSDT",
    "UMAUSDT",
    "BANDUSDT",
    "AUDIOUSDT",
    "CRVUSDT",
    "FIOUSDT",
    "THETAUSDT",
    "LUNAUSDT",
    "KMDUSDT",
    "CTXCUSDT",
    "FORTHUSDT",
    "PHAUSDT",
    "DNTUSDT",
    "WTCUSDT",
    "SHIBUSDT",
    "STPTUSDT",
    "PEOPLEUSDT",
    "ORNUSDT",
    "AIONUSDT",
    "SYSUSDT",
    "MATICUSDT",
    "DOTUSDT",
    "GRTUSDT",
    "TVKUSDT",
    "ATMUSDT",
    "BNXUSDT",
    "DARUSDT",
    "PYRUSDT",
    "REQUSDT",
    "FUNUSDT",
    "XLMUSDT",
    "NUUSDT",
    "PAXGUSDT",
    "WRXUSDT",
    "MKRUSDT",
    "ARDRUSDT",
    "PNTUSDT",
    "HIGHUSDT",
    "ARUSDT",
    "RAYUSDT",
    "ZENUSDT",
    "LRCUSDT",
    "JASMYUSDT",
    "LAZIOUSDT",
    "WNXMUSDT",
    "ADAUSDT",
    "TWTUSDT",
    "ADXUSDT",
    "UNIUSDT",
    "HIVEUSDT",
    "ZECUSDT",
    "CHZUSDT",
    "MBLUSDT",
    "RAMPUSDT",
    "BALUSDT",
    "MDTUSDT",
    "WINUSDT",
    "TRIBEUSDT",
    "SOLUSDT",
    "MITHUSDT",
    "BNBUSDT",
    "ATAUSDT",
    "IOSTUSDT",
    "UNFIUSDT",
    "GLMRUSDT",
    "DASHUSDT",
    "MTLUSDT",
    "FILUSDT",
    "KEYUSDT",
    "SANTOSUSDT",
    "DODOUSDT",
    "SRMUSDT",
    "DEGOUSDT",
    "VOXELUSDT",
    "DATAUSDT",
    "AAVEUSDT",
    "VTHOUSDT",
    "NBSUSDT",
    "QIUSDT",
    "VITEUSDT",
    "EPSUSDT",
    "SANDUSDT",
    "XVSUSDT",
    "ACHUSDT",
    "JSTUSDT",
    "RNDRUSDT",
    "STXUSDT",
    "LINKUSDT",
    "MANAUSDT",
    "POLSUSDT",
    "LSKUSDT",
    "DENTUSDT",
    "RUNEUSDT",
    "AUDUSDT",
    "NKNUSDT",
    "ARPAUSDT",
    "EOSUSDT",
    "PERLUSDT",
    "JOEUSDT",
    "KNCUSDT",
    "OCEANUSDT",
    "GBPUSDT",
    "FIDAUSDT",
    "IOTAUSDT",
    "FIROUSDT",
    "DEXEUSDT",
    "GTCUSDT",
    "BNTUSDT",
    "NEOUSDT",
    "CAKEUSDT",
    "DOCKUSDT",
    "SUPERUSDT",
    "RAREUSDT",
    "ENSUSDT",
    "AUTOUSDT",
    "STRAXUSDT",
    "MINAUSDT",
    "BAKEUSDT",
    "SCUSDT",
    "QTUMUSDT",
    "UTKUSDT",
    "BARUSDT",
    "YFIUSDT",
    "BETAUSDT",
    "CTKUSDT",
    "RLCUSDT",
    "LTOUSDT",
    "YFIIUSDT",
    "FLOWUSDT",
    "FARMUSDT",
    "BELUSDT",
    "POWRUSDT",
    "CHESSUSDT",
    "SLPUSDT",
    "SUSDUSDT",
    "ETCUSDT",
    "MASKUSDT",
    "LITUSDT",
    "ALPACAUSDT",
    "HOTUSDT",
    "ZRXUSDT",
    "FTTUSDT",
    "STORJUSDT",
    "FTMUSDT",
    "AVAUSDT",
    "SFPUSDT",
    "ACMUSDT",
    "ANKRUSDT",
]
